global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'ccloudexporter'
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: <CCLOUD-API-KEY>
      password: <CCLOUD-API-SECRET>
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-xxx

