apiVersion: v1
kind: Service
metadata:
  labels:
    app: #{cluster}#-svc
  name: #{cluster}#-svc
spec:
  ports:
  - name: metrics
    port: 2112
    protocol: TCP
    targetPort: 2112
  selector:
    app: #{cluster}#-svc
  type: ClusterIP
