apiVersion: v1
kind: Service
metadata:
  name: cloudexporter
  namespace: cloudexporter
spec:
  ports:
  - port: 2112
    protocol: TCP
    targetPort: 2112
  selector:
    app: cloudexporter
  type: ClusterIP
