apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    #prometheus.io/port: "metrics"
  name: cloudexporter
spec:
  ports:
  - name: metrics
    port: 2112
    protocol: TCP
    targetPort: 2112
  selector:
    app: cloudexporter
  type: ClusterIP
