global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ccloud_metrics
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_timestamps: true
    static_configs:
      - targets:
          - ccloud_exporter:2112
          - kafka-lag-exporter:9999
